Resources:
  # define here your s3 bucket name
  Paramters:
    S3KeyParameter:
      Trype: String
      Dafault: "s3 bucket key"
  # cria permissão para execussão da função lambda
  LambdaExecutionRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: "sts:AssumeRole"
  # cria função lambda
  MyLambdaFunction:
    Type: "AWS::Lambda::Function"
    Properties:
      Handler: "<DEFINIR FUNÇÃO QUE SERA EXECUTADA>"
      Role: !GetAtt [ LambdaExecutionRole, Arn ]
      Code:
        S3Bucket: 
          Ref: "S3KeyParameter"
        S3Key: "1-example.zip"
      Runtime: "python3.x"
      Timeout: 5
  # cria permissão para execussaço da lambda pela step function 
  StatesExecutionRole:
  Type: "AWS::IAM::Role"
  Properties:
    AssumeRolePolicyDocument:
      Version: "2012-10-17"
      Statement:
        - Effect: "Allow"
          Principal:
            Service:
              - !Sub states.${AWS::Region}.amazonaws.com
          Action: "sts:AssumeRole"
    Path: "/"
    Policies:
      - PolicyName: StatesExecutionPolicy
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - "lambda:InvokeFunction"
              Resource: "*"
  # cria step function
  MyStateMachine:
    Type: "AWS::StepFunctions::StateMachine"
    Properties:
      StateMachineName: "step-one"
      DefinitionS3Location: 
        Bucket:
          Ref: S3KeyParameter
        Key: "1-example.json"
      RoleArn: !GetAtt [ StatesExecutionRole, Arn ]